services:
  knowgenai:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: ffadlymii/knowgenai
    restart: always
    ports:
      - "3001:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NEXTAUTH_URL=https://knowgen-ai-dev.metrodata.web.id
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - NEXTAUTH_SECRET=dB3SrjkBgpsRS4RjrLDgKaqfteF4y4m7eQCrA7OiRVs=